version: '3.8'
services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./voiceStats.db:/usr/src/app/voiceStats.db
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "node", "-e", "require('node:process').exit(process.uptime() < 3 ? 1 : 0)"]
      interval: 30s
      timeout: 10s
      retries: 3